# Generated by Django 2.2.5 on 2019-10-25 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=5, verbose_name='Название факультета')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty_name', models.CharField(max_length=50, verbose_name='Название специальности')),
                ('faculty_name_of_specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NURE_marks.Faculty', verbose_name='Выберите факультет')),
            ],
        ),
        migrations.CreateModel(
            name='University_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.PositiveSmallIntegerField(verbose_name='Номер группы')),
                ('year_of_receipt', models.PositiveSmallIntegerField(default=2019, verbose_name='Год начала обучения')),
                ('group_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NURE_marks.Faculty', verbose_name='Факультет группы')),
                ('specialty_of_group', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='group_faculty', chained_model_field='faculty_name_of_specialty', on_delete=django.db.models.deletion.CASCADE, show_all=True, to='NURE_marks.Specialty')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_department', models.CharField(blank=True, max_length=20, null=True)),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Teachers'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('group_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NURE_marks.Faculty', verbose_name='Факультет группы')),
                ('specialty_of_group', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='group_faculty', chained_model_field='faculty_name_of_specialty', on_delete=django.db.models.deletion.CASCADE, show_all=True, to='NURE_marks.Specialty')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Students'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student_group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='student_group', to='NURE_marks.University_Group')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NURE_marks.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplineForGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='specialty_of_group', chained_model_field='specialty_of_group', on_delete=django.db.models.deletion.CASCADE, show_all=True, to='NURE_marks.University_Group')),
                ('group_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NURE_marks.Faculty', verbose_name='Факультет группы')),
                ('laboratory_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_teacher', to='NURE_marks.Teacher')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer', to='NURE_marks.Teacher')),
                ('practical_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_teacher', to='NURE_marks.Teacher')),
                ('specialty_of_group', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='group_faculty', chained_model_field='faculty_name_of_specialty', on_delete=django.db.models.deletion.CASCADE, show_all=True, to='NURE_marks.Specialty')),
                ('subject', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='specialty_of_group', chained_model_field='specialty_of_group', on_delete=django.db.models.deletion.CASCADE, show_all=True, to='NURE_marks.Subject')),
            ],
        ),
    ]
