# Generated by Django 2.2.5 on 2019-10-06 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='University_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default='[default group name]', max_length=50)),
                ('course_number_of_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NURE_marks.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some_info', models.CharField(default='[some default info]', max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty_name', models.CharField(max_length=50)),
                ('faculty_name_of_specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NURE_marks.Faculty')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='specialty_name_of_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NURE_marks.Specialty'),
        ),
    ]
