# Generated by Django 2.2.5 on 2019-10-25 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NURE_marks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplineforgroup',
            name='laboratory_teacher',
        ),
        migrations.RemoveField(
            model_name='disciplineforgroup',
            name='lecturer',
        ),
        migrations.RemoveField(
            model_name='disciplineforgroup',
            name='practical_teacher',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
