# Generated by Django 2.2.5 on 2019-10-07 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NURE_marks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Students'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='university_group',
            name='course_number_of_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NURE_marks.Specialty'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
