# Generated by Django 2.2.5 on 2019-10-07 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NURE_marks', '0002_auto_20191007_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university_group',
            old_name='course_number_of_group',
            new_name='Specialty_of_group',
        ),
    ]
