# Generated by Django 2.2.5 on 2019-10-25 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NURE_marks', '0002_auto_20191025_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_department', models.CharField(blank=True, max_length=20, null=True)),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Teachers'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='disciplineforgroup',
            name='laboratory_teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_teacher', to='NURE_marks.Teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disciplineforgroup',
            name='lecturer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lecturer', to='NURE_marks.Teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disciplineforgroup',
            name='practical_teacher',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='practical_teacher', to='NURE_marks.Teacher'),
            preserve_default=False,
        ),
    ]
