# Generated by Django 2.2.5 on 2019-10-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NURE_marks', '0003_auto_20191007_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='university_group',
            name='course_number',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
