# Generated by Django 2.2.5 on 2019-10-27 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NURE_marks', '0003_auto_20191025_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplineforgroup',
            name='lecturer',
        ),
        migrations.AddField(
            model_name='subject',
            name='lecturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecturer', to='NURE_marks.Teacher'),
        ),
        migrations.AlterField(
            model_name='disciplineforgroup',
            name='laboratory_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_teacher', to='NURE_marks.Teacher'),
        ),
        migrations.AlterField(
            model_name='disciplineforgroup',
            name='practical_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practical_teacher', to='NURE_marks.Teacher'),
        ),
    ]
