# Generated by Django 2.2.5 on 2019-10-27 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NURE_marks', '0004_auto_20191027_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NURE_marks.University_Group'),
        ),
        migrations.AddField(
            model_name='mark',
            name='marks',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='NURE_marks.Student'),
        ),
        migrations.AddField(
            model_name='subject',
            name='number_of_laboratory_lessons',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='number_of_lectures',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='number_of_practical_lessons',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mark',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NURE_marks.DisciplineForGroup'),
        ),
    ]
