# Generated by Django 2.2.5 on 2019-10-07 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NURE_marks', '0005_auto_20191007_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university_group',
            name='Specialty_of_group',
        ),
        migrations.AddField(
            model_name='university_group',
            name='group_faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NURE_marks.Faculty', verbose_name='Факультет группы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university_group',
            name='specialty_of_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NURE_marks.Specialty', verbose_name='Выберите специальность'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_name',
            field=models.CharField(max_length=5, verbose_name='Название факультета'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='faculty_name_of_specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NURE_marks.Faculty', verbose_name='Выберите факультет'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='specialty_name',
            field=models.CharField(max_length=50, verbose_name='Название специальности'),
        ),
        migrations.AlterField(
            model_name='university_group',
            name='group_name',
            field=models.CharField(default='[ХЗ, оставлять это чи нет]', max_length=50),
        ),
        migrations.AlterField(
            model_name='university_group',
            name='year_of_receipt',
            field=models.PositiveSmallIntegerField(default=2019, verbose_name='Год начала обучения'),
        ),
    ]
