# Generated by Django 2.2.5 on 2019-10-08 22:43

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('NURE_marks', '0009_auto_20191009_0130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='newcontinent',
            new_name='continent',
        ),
        migrations.RemoveField(
            model_name='continent',
            name='name',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='newcountry',
        ),
        migrations.AddField(
            model_name='continent',
            name='continent',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='country',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='continent', chained_model_field='continent', default=1, on_delete=django.db.models.deletion.CASCADE, to='NURE_marks.Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='street',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=45)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NURE_marks.Country')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='area',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='country', chained_model_field='country', default=1, on_delete=django.db.models.deletion.CASCADE, to='NURE_marks.Area'),
            preserve_default=False,
        ),
    ]
