# Generated by Django 2.2.5 on 2019-10-09 12:06

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('NURE_marks', '0010_auto_20191009_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university_group',
            name='specialty_of_group',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='group_faculty', chained_model_field='group_faculty', on_delete=django.db.models.deletion.CASCADE, to='NURE_marks.Specialty'),
        ),
    ]
