# Generated by Django 2.2.5 on 2019-10-09 12:30

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('NURE_marks', '0011_auto_20191009_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='location',
            name='area',
        ),
        migrations.RemoveField(
            model_name='location',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='location',
            name='country',
        ),
        migrations.RemoveField(
            model_name='managedfile',
            name='type',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='m_file',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='type',
        ),
        migrations.RemoveField(
            model_name='university_group',
            name='group_name',
        ),
        migrations.AlterField(
            model_name='university_group',
            name='specialty_of_group',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='group_faculty', chained_model_field='faculty_name_of_specialty', on_delete=django.db.models.deletion.CASCADE, to='NURE_marks.Specialty'),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Continent',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='FileType',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='ManagedFile',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
