# Generated by Django 2.2.5 on 2019-10-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NURE_marks', '0012_auto_20191009_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='university_group',
            name='group_number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Номер группы'),
            preserve_default=False,
        ),
    ]
