# Generated by Django 2.2.5 on 2019-10-09 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NURE_marks', '0013_university_group_group_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='university_group',
            name='student',
            field=models.ForeignKey(default=1, limit_choices_to={'groups__name': 'Students'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
