# Generated by Django 2.2.5 on 2019-10-09 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NURE_marks', '0014_university_group_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_group', to='NURE_marks.University_Group'),
            preserve_default=False,
        ),
    ]
