# Generated by Django 2.2.5 on 2019-10-09 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NURE_marks', '0015_student_student_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='some_info',
        ),
    ]
