# Generated by Django 2.2.5 on 2019-10-09 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NURE_marks', '0016_remove_student_some_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university_group',
            name='student',
        ),
        migrations.AlterField(
            model_name='student',
            name='student',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Students'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
